## Exercícios

1 - Crie um array de uma dimensão chamado arr com todos os valores inteiros entre 1 e 50.

2 - Usando o array criado acima multiple todos os valores impares por -1.

3 - Transforme arr em um array de duas dimensões (dica, use reshape).

4 - Descubra: a média, mediana, o desvio padrão, o valor do primeiro quartil, o valor do terceiro quartil e o IQR do array arr.

5 - Encontre a média do array abaixo:

arr2 = np.array([[12,12,12],[15,15,15],[20,20,20]])

6 - Monte um código que transforme a lista abaixo em um array de duas dimensões. Depois disso ele deve substituir os valores na diagonal da matriz por zero.

ls = [[3,3,3],[2,2,2],[1,1,1]]

In [120]:
import numpy as np

In [131]:
## Questão 1

arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [132]:
## Questão 2

for i,value in enumerate(arr):
    if value % 2 != 0:
        arr[i] = value*-1
        
arr

array([ -1,   2,  -3,   4,  -5,   6,  -7,   8,  -9,  10, -11,  12, -13,
        14, -15,  16, -17,  18, -19,  20, -21,  22, -23,  24, -25,  26,
       -27,  28, -29,  30, -31,  32, -33,  34, -35,  36, -37,  38, -39,
        40, -41,  42, -43,  44, -45,  46, -47,  48, -49,  50])

In [133]:
## Questão 3

arr = arr.reshape(25,2)
arr

array([[ -1,   2],
       [ -3,   4],
       [ -5,   6],
       [ -7,   8],
       [ -9,  10],
       [-11,  12],
       [-13,  14],
       [-15,  16],
       [-17,  18],
       [-19,  20],
       [-21,  22],
       [-23,  24],
       [-25,  26],
       [-27,  28],
       [-29,  30],
       [-31,  32],
       [-33,  34],
       [-35,  36],
       [-37,  38],
       [-39,  40],
       [-41,  42],
       [-43,  44],
       [-45,  46],
       [-47,  48],
       [-49,  50]])

In [139]:
## Questão 4

media = arr.mean()
mediana = np.quantile(arr,0.5)
desvio = arr.std()

qart1 = np.quantile(arr,0.25)
qart3 = np.quantile(arr,0.75)

iqr = qart3 - qart1


print(f'Media:{media}\nMediana:{mediana}\nDesvio Padrão:{desvio}\nQuartil 1:{qart1}\nQuartil 3:{qart3}\nIQR:{iqr}')

Media:0.5
Mediana:0.5
Desvio Padrão:29.295904150580505
Quartil 1:-24.5
Quartil 3:25.5
IQR:50.0


In [142]:
## Questão 5

arr2 = np.array([[12,12,12],[15,15,15],[20,20,20]])

arr2.mean()

15.666666666666666

In [143]:
## Questão 6

ls = [[3,3,3],[2,2,2],[1,1,1]]

def diag_zero(ls):
    arr = np.array(ls)
    
    for i,value in enumerate(arr):
        arr[i][i] = 0
        
    return arr

In [144]:
diag_zero(ls)

array([[0, 3, 3],
       [2, 0, 2],
       [1, 1, 0]])